<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ../../../../../static/models/potion.glb
-->

<script>
	import { T } from "@threlte/core";
	import { useGltf } from "@threlte/extras";

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const gltf = useGltf("/models/potion.glb");
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group scale={6} position.y={1.65}>
			<T.Mesh
				geometry={gltf.nodes.mesh2068853349.geometry}
				material={gltf.materials.mat24}
			/>
			<T.Mesh
				geometry={gltf.nodes.mesh2068853349_1.geometry}
				material={gltf.materials.mat2}
			/>
			<T.Mesh
				geometry={gltf.nodes.mesh2068853349_2.geometry}
				material={gltf.materials.mat19}
			/>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
