<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ../../../../../static/models/bhbus.glb
-->

<script>
	import { T } from "@threlte/core";
	import { useGltf } from "@threlte/extras";
	import { degToRad } from "three/src/math/MathUtils.js";

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const gltf = useGltf("/models/bhbus.glb");
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group scale={0.8} position.y={1.75} rotation.y={degToRad(90)}>
			<T.Mesh
				geometry={gltf.nodes.Plane_1.geometry}
				material={gltf.materials.base}
			/>
			<T.Mesh
				geometry={gltf.nodes.Plane_2.geometry}
				material={gltf.materials.front}
			/>
			<T.Mesh
				geometry={gltf.nodes.Plane_3.geometry}
				material={gltf.materials.back}
			/>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
