<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/models/capsule.glb src/components/gachapon/models/capsule
-->

<script>
	import { T } from "@threlte/core";
	import { useGltf } from "@threlte/extras";

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		color = "#fde047",
		positionUp = [0, 0, 0],
		positionDown = [0, 0.2, 0],
		...props
	} = $props();

	const gltf = useGltf("/models/capsule.glb");
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.CapsuleTop.geometry}
			material={gltf.nodes.CapsuleTop.material}
			position={positionUp}
		>
			<T.MeshStandardMaterial
				{color}
				roughness={0.35}
				metalness={0.05}
				clearcoat={0.8}
				clearcoatRoughness={0.1}
			/>
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.CapsuleBottom.geometry}
			material={gltf.nodes.CapsuleBottom.material}
			position={positionDown}
			rotation={[0, 0, -Math.PI]}
		>
			<T.MeshStandardMaterial
				{color}
				roughness={0.35}
				metalness={0.05}
				clearcoat={0.8}
				clearcoatRoughness={0.1}
			/>
		</T.Mesh>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
