<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ../../../../../static/models/coin-bag.glb
-->

<script>
	import { T } from "@threlte/core";
	import { useGltf } from "@threlte/extras";

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const gltf = useGltf("/models/coin-bag.glb");
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group
			rotation={[-Math.PI / 2, 0, 0]}
			scale={125}
			position.y={0.3}
			position.z={0.05}
		>
			<T.Mesh
				geometry={gltf.nodes.Bag_Coins_1.geometry}
				material={gltf.materials.Bag}
			/>
			<T.Mesh
				geometry={gltf.nodes.Bag_Coins_2.geometry}
				material={gltf.materials.Gold}
			/>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
