<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ../../../../../static/models/crystal.glb
-->

<script>
	import { T } from "@threlte/core";
	import { useGltf } from "@threlte/extras";

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const gltf = useGltf("/models/crystal.glb");
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group rotation={[-Math.PI / 2, 0, 0]} scale={500} position.y={1.25}>
			<T.Mesh
				name="Mineral_1"
				geometry={gltf.nodes.Mineral_1.geometry}
				material={gltf.materials.Grey}
				morphTargetDictionary={gltf.nodes.Mineral_1.morphTargetDictionary}
				morphTargetInfluences={gltf.nodes.Mineral_1.morphTargetInfluences}
			/>
			<T.Mesh
				name="Mineral_2"
				geometry={gltf.nodes.Mineral_2.geometry}
				material={gltf.materials.Pink}
				morphTargetDictionary={gltf.nodes.Mineral_2.morphTargetDictionary}
				morphTargetInfluences={gltf.nodes.Mineral_2.morphTargetInfluences}
				material.color="#0ea5e9"
			/>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
