<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ../../../../../static/models/earbud.glb
-->

<script>
	import { T } from "@threlte/core";
	import { useGltf } from "@threlte/extras";
	import { degToRad } from "three/src/math/MathUtils.js";

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const gltf = useGltf("/models/earbud.glb");
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group scale={0.375} position.y={1.75} rotation.y={degToRad(30)}>
			<T.Mesh
				geometry={gltf.nodes.Object_0.geometry}
				material={gltf.materials.cEVcwrpGKjNUrED}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_0_1.geometry}
				material={gltf.materials.DrEQLAPBkLNlpSM}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_0_2.geometry}
				material={gltf.materials.FJixwyYXpYmTghW}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_0_3.geometry}
				material={gltf.materials.czaVLhHNccVShhr}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_0_4.geometry}
				material={gltf.materials.OXPzgZBrHvcYhRk}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_0_5.geometry}
				material={gltf.materials.BQKMNbgpcCWqzPH}
			/>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
