<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ../../../../../static/models/mp3-player.glb
-->

<script>
	import { T } from "@threlte/core";
	import { useGltf } from "@threlte/extras";
	import { degToRad } from "three/src/math/MathUtils.js";

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const gltf = useGltf("/models/mp3-player.glb");
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group
			scale={[0.05, 0.05, 0.05]}
			rotation.x={degToRad(90)}
			rotation.z={degToRad(-90)}
			position={[-1.5, 3.5, -0.75]}
		>
			<T.Mesh
				geometry={gltf.nodes.Text001_1.geometry}
				material={gltf.materials["10___Default"]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Text001_1_1.geometry}
				material={gltf.materials["07___Default"]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Text001_1_2.geometry}
				material={gltf.materials["02___Default"]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Text001_1_3.geometry}
				material={gltf.materials["01___Default"]}
			/>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
