<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ../../../../../static/models/pin-button.glb
-->

<script>
	import { T } from "@threlte/core";
	import { useGltf } from "@threlte/extras";
	import { degToRad } from "three/src/math/MathUtils.js";

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const gltf = useGltf("/models/pin-button.glb");
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group position.y={1.7} rotation.y={degToRad(90)}>
			<T.Group rotation.x={degToRad(45)}>
				<T.Mesh
					geometry={gltf.nodes.Object_0.geometry}
					material={gltf.materials.M_BUTTON_COVER}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_0_1.geometry}
					material={gltf.materials.M_BUTTON_BACK}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_0_2.geometry}
					material={gltf.materials.M_SAFETY_PIN}
				/>
			</T.Group>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
