<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ../../../../../static/models/fidget-spinner.glb
-->

<script lang="ts">
	import { T, useTask } from "@threlte/core";
	import { useGltf } from "@threlte/extras";
	import { degToRad } from "three/src/math/MathUtils.js";
	import { onMount } from "svelte";
	import { AUDIO_ELEMENTS, DEFAULT_VOLUME, playAudio } from "$lib/audio";

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const gltf = useGltf("/models/fidget-spinner.glb");

	let spinAudio = $state<HTMLAudioElement>();
	let spinAudioVolume = $state(0);

	$effect(() => {
		if (!spinAudio) return;
		spinAudio.volume = spinAudioVolume;
	});

	let isDragging = $state(false);
	let lastX = $state(0);
	let lastY = $state(0);
	let velocity = $state(0);
	let rotationX = $state(0);

	const idleSpeed = 0.3;
	const friction = 0.99;

	const onPointerDown = (e: MouseEvent | TouchEvent) => {
		isDragging = true;
		// @ts-ignore: already handled with `?.`
		lastX = e?.clientX || e?.touches?.[0]?.clientX || 0;
		// @ts-ignore: already handled with `?.`
		lastY = e?.clientY || e?.touches?.[0]?.clientY || 0;
	};

	const onPointerMove = (e: MouseEvent | TouchEvent) => {
		if (!isDragging) return;

		// @ts-ignore: already handled with `?.`
		const clientX = e?.clientX || e?.touches?.[0]?.clientX || 0;
		// @ts-ignore: already handled with `?.`
		const clientY = e?.clientY || e?.touches?.[0]?.clientY || 0;

		const deltaX = clientX - lastX;
		const deltaY = clientY - lastY;
		const drag = deltaX + deltaY;

		velocity = drag * 0.1;
		lastX = clientX;
		lastY = clientY;
	};

	const onPointerUp = () => {
		isDragging = false;
	};

	useTask((delta) => {
		rotationX += (velocity + idleSpeed) * delta;
		velocity *= friction;
		spinAudioVolume = Math.min(
			0.5,
			Math.max(0, ((Math.abs(velocity) - 1) / 9) * DEFAULT_VOLUME),
		);
	});

	onMount(() => {
		spinAudio = AUDIO_ELEMENTS.get("fidget-spinner")!;
		spinAudio.volume = 0;
		spinAudio.loop = true;
		playAudio("fidget-spinner");
		return () => spinAudio?.pause();
	});
</script>

<svelte:window
	onpointermove={onPointerMove}
	ontouchmove={onPointerMove}
	onpointerup={onPointerUp}
	ontouchend={onPointerUp}
	onpointerdown={onPointerDown}
	ontouchstart={onPointerDown}
/>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group
			scale={2.5}
			position.y={1.75}
			rotation.x={rotationX}
			rotation.y={degToRad(90)}
		>
			<T.Mesh
				geometry={gltf.nodes.Object_1.geometry}
				material={gltf.materials.Plastic_001}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_1_1.geometry}
				material={gltf.materials.Alloy}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_1_2.geometry}
				material={gltf.materials.Plastic_002}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_1_3.geometry}
				material={gltf.materials.Weights}
			/>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
