<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ../../../../../static/models/keys.glb
Author: combine_soldier (https://sketchfab.com/combine_soldier)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/keys-with-tag-game-ready-mobile-friendly-a9bced5ac95f49ff849ae3377d391e47
Title: Keys With Tag [Game-Ready, Mobile Friendly]
-->

<script>
	import { T } from "@threlte/core";
	import { useGltf } from "@threlte/extras";
	import { degToRad } from "three/src/math/MathUtils.js";

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const gltf = useGltf("/models/keys.glb");
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group rotation.y={degToRad(-15)} position={[-0.1, 1.6, 0]}>
			<T.Mesh
				geometry={gltf.nodes.item_keys_bake_0.geometry}
				material={gltf.materials.bake}
				scale={0.2}
				rotation={[degToRad(-90), degToRad(90), degToRad(0)]}
			/>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
