<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ../../../../../static/models/note.glb
-->

<script>
	import { getLocale } from "$lib/paraglide/runtime";
	import { T } from "@threlte/core";
	import { useGltf } from "@threlte/extras";
	import { DoubleSide } from "three";
	import { degToRad } from "three/src/math/MathUtils.js";

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const gltf = useGltf("/models/note.glb");
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group scale={1.5} position.y={1.7} rotation.y={degToRad(90)}>
			<T.Mesh
				geometry={gltf.nodes.NoteEmpty.geometry}
				material={gltf.materials.Empty}
				rotation={[Math.PI / 2, 0, 0]}
				scale={[0.98, 1, 0.51]}
				material.side={DoubleSide}
			/>
			<T.Mesh
				geometry={gltf.nodes.NoteEnglish.geometry}
				material={getLocale() === "en"
					? gltf.materials.English
					: gltf.materials.Portuguese}
				rotation={[Math.PI / 2, 0, 0]}
				scale={[0.98, 1, 0.51]}
				position.z={0.01}
				material.side={DoubleSide}
			/>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
