<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ../../../../../static/models/snack.glb
-->

<script>
	import { T } from "@threlte/core";
	import { useGltf } from "@threlte/extras";
	import { degToRad } from "three/src/math/MathUtils.js";

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const gltf = useGltf("/models/snack.glb");
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group rotation.z={degToRad(45)} position.y={1.75}>
			<T.Group scale={0.3} rotation.y={degToRad(90)}>
				<T.Mesh geometry={gltf.nodes.Cube001.geometry}>
					<T.MeshPhysicalMaterial
						color="#7B3F00"
						roughness={0.4}
						metalness={0}
						clearcoat={0.2}
						clearcoatRoughness={0.5}
					/>
				</T.Mesh>
				<T.Mesh geometry={gltf.nodes.Cube001_1.geometry}>
					<T.MeshPhysicalMaterial
						color="#234AA3"
						roughness={0.6}
						metalness={0}
						clearcoat={0.15}
						clearcoatRoughness={0.4}
						reflectivity={0.3}
						sheen={0.2}
					/>
				</T.Mesh>
			</T.Group>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
