<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ../../../../../static/models/bottlecap.glb
-->

<script>
	import { T } from "@threlte/core";
	import { useGltf } from "@threlte/extras";
	import { DoubleSide } from "three";
	import { degToRad } from "three/src/math/MathUtils.js";

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const gltf = useGltf("/models/bottlecap.glb");
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.Cylinder_Cylinder001.geometry}
			material={gltf.materials.phong1SG}
			scale={25}
			position.x={-0.1}
			position.y={1.8}
			rotation.x={degToRad(90)}
			rotation.z={degToRad(-90)}
			material.side={DoubleSide}
		/>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
