<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ../../../../../static/models/fork.glb
-->

<script>
	import { T } from "@threlte/core";
	import { useGltf } from "@threlte/extras";
	import { degToRad } from "three/src/math/MathUtils.js";

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const gltf = useGltf("/models/fork.glb");
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh
			scale={0.5}
			position.y={2.1}
			position.x={-0.35}
			rotation={[degToRad(-90), degToRad(-45), degToRad(-90)]}
			geometry={gltf.nodes.Node.geometry}
			material={gltf.materials.lambert2SG}
			material.metalness={1}
			material.roughness={0.2}
		/>
		<T.DirectionalLight
			intensity={0.1}
			position={[10, 10, -10]}
			oncreate={(ref) => {
				ref.lookAt(0, 1.75, 0);
			}}
		/>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
