<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ../../../../../../static/models/present.glb
-->

<script>
	import { T } from "@threlte/core";
	import { useGltf } from "@threlte/extras";
	import { degToRad } from "three/src/math/MathUtils.js";

	let { boxY = 0, lidY = 0, scale = 1, ...props } = $props();

	const gltf = useGltf("/models/present.glb");
</script>

<T.Group dispose={false} position.y={1} {scale} {...props}>
	{#await gltf then gltf}
		<T.Group scale={12} rotation.y={degToRad(90)}>
			<T.Mesh
				geometry={gltf.nodes.Box.geometry}
				material={gltf.materials["Material.001"]}
				position.y={boxY}
			/>
			<T.Mesh
				geometry={gltf.nodes.Lid.geometry}
				material={gltf.materials["Material.001"]}
				position.y={lidY}
			/>
		</T.Group>
	{/await}
</T.Group>
