<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ../../../../../static/models/sword.glb
-->

<script>
	import { T } from "@threlte/core";
	import { useGltf } from "@threlte/extras";
	import { degToRad } from "three/src/math/MathUtils.js";

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const gltf = useGltf("/models/sword.glb");
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group position.y={0.6}>
			<T.Group rotation={[degToRad(-90), 0, 0]} scale={150}>
				<T.Mesh
					geometry={gltf.nodes.Sword_1.geometry}
					material={gltf.materials.DarkSteel}
				/>
				<T.Mesh
					geometry={gltf.nodes.Sword_2.geometry}
					material={gltf.materials.DarkWood}
				/>
				<T.Mesh
					geometry={gltf.nodes.Sword_3.geometry}
					material={gltf.materials.LightWood}
				/>
				<T.Mesh
					geometry={gltf.nodes.Sword_4.geometry}
					material={gltf.materials.LightSteel}
				/>
				<T.Mesh
					geometry={gltf.nodes.Sword_5.geometry}
					material={gltf.materials.Steel}
				/>
			</T.Group>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
